# Site settings
title: Srikanth Mokkapati
#twitter_username:
name: Srikanth Mokkapati

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
#  - title: Blog
#    url: 
 - title: GitHub
   url: https://github.com/srikanth-mokkapati
#  - title: StackOverflow
#    url: 
#  - title: DZone
#    url: 
 - title: LinkedIn
   url: https://www.linkedin.com/in/srikanth-mokkapati-322980135

#Any buzzword skills you want to include
skills:
 - Java
 - Spring MVC/SpringBoot
 - Microservices
 - Git
 - Python
 - SQL, NoSQL
 - MS-SQL, MySQL, MongoDB, Cassandra
 - API design
 - Maven, JSON, REST
 - Django Rest Framework
 - JWT, ORM, JPA
 - SONAR
 - BigData
 - Docker and Azure
 - Automation and Machine Learning
 - Technical Architecture

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed:

#Work experience is required
roles:
 - title: Software Product Developer
   start: January, 2020
   end: Ongoing
   employer: OpsRamp, Hyderabad, India
   description: Rapidly Growing IT Operations Management Platform. Working as a Java Backend Developer focused on Microservices Development and Big Data Management.<a href="https://www.opsramp.com/" taget="_blank">OpsRamp</a>.
 - title: Software Engineer
   start: May, 2019
   end: December, 2019
   employer: Kloud Maaya Software and Data Technologies, Hyderabad, India
   description: Cloud and Mobile focused IT Services Startup with Operations in India and US. Worked as a Java Backend Engineer, developing APIs in a Microservices Environment.
 - title: Assistant Systems Engineer
   start: December, 2017
   end: May, 2019
   employer: Tata Consultancy Services, Chennai, India
   description: Indian IT MNC Leader with Global Operations in Multiple Sectors. Worked as a Java and Python Developer in Machine Learning aided Automation.

#Education is required
education:
 - level: Bachelor of Technology (B.Tech.)
   date: 2017
   subject: Electronics and Communication Engineering
   school: VR Siddhartha College of Engineering, Vijayawada, Andhra Pradesh, India.

#This section is optional (as is the image link below)
# coursera:
#    profileurl: 
#    courses:
#     - title: 
#       link: 
#       optionalimage: 
#       date: 
#     - title: 
#       link: 
#       optionalimage: 
#       date: 

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
# speakerdeck:
#    profileurl:
#    talks:
#     - title: 
#       speakerdeckId: 
#       conference: 
#     - title: 
#       speakerdeckId: 
#       conference: 

#List of interesting Github repo/projects to include - optional
github:
 - srikanth-mokkapati/srikanth-mokkapati.github.io

#Stackoverflow flair is optional
# stackoverflow:
#    profileurl:
#    flairimageurl:

intro: |
  I am an Backend Engineer with around 3 years of experience working in IT. I primarily work with Java based REST API Development leveraging Technologies such as JSON, MongoDB, MS-SQL, Docker and Microservices.  <br/><br/>
  Apart from Java, I like working with Python and has Experience in Automation aided by Machine Learning. I am interested in Fields of BigData and Data Engineering.<br/><br/>
  Working in both MNCs and Startups, I believe a good Work-Life balance is required for ensured Productivity.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Java</strong>: My current role uses Java as the primary language and have been building applications in Java for the last 1.5 years. I am familiar with a range of Java libraries, such as Spring MVC/SpringBoot, Jackson, GSON, Retrofit, Functional Streams (Java 8+) and JPA. I use these libraries to build Microservices driven by REST APIs. <br/><br/>
   <strong>Python</strong>: I enjoy simple syntax of Python and writing simple scripts for automating mundane tasks. Professionally worked with libraries such as requests, pandas and sk-learn to drive Machine Learning aided Automation. Wrote simple apps to learn and Experiment with Django Rest Framework, ORM with SQLite and Fast API. <br/><br/>
   <strong>MongoDB</strong>: I have worked on MongoDB based Applications to evolve schema with Business Requirements while maintaining performance. We leveraged its great Java Library support and query capabilities for complex functional requirements.</a>.<br/><br/>
   <strong>SQL</strong>: I have worked mainly with MS-SQL and MySQL and experimented a little bit with SQLite and Postgres. <br/><br/>
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with Git, Maven, Sonar, Jenkins, etc. I have experience with an Unit Testing and Functional Testing using testing frameworks and Embedded DBs.<br/><br/>
   <strong>Other Technical Interests</strong>: I am interested in experimenting with latest technologies and building simple side projects for learning purpose. In free time, I try to keep myself updated with latest trends reading various blog posts and listening to podcasts. <br/><br/>